name: Generate and Commit CSV

on:
  schedule:
    # Runs every day at 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch:  # allows manual trigger

permissions:
  contents: write  # allow push access

jobs:
  generate-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          ref: data-updates   # branch to update or create

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run Python script
        run: python create_csv.py

      - name: Commit and push CSV to data-updates branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/latest.csv
          git commit -m "Update latest.csv - $(date -u +"%Y-%m-%d %H:%M:%S")" || echo "No changes to commit"
          git push origin data-updates
