name: Generate and Commit CSV

on:
  schedule:
    # Runs every day at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0  # fetch full history so we can branch off

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run Python script
        run: python create_csv.py

      - name: Switch/create data-updates branch
        run: |
          git fetch origin || true
          if git rev-parse --verify origin/data-updates >/dev/null 2>&1; then
            git checkout data-updates
            git pull origin data-updates
          else
            git checkout -b data-updates
          fi

      - name: Commit and push CSV to data-updates branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/latest.csv
          git commit -m "Update latest.csv - $(date -u +"%Y-%m-%d %H:%M:%S")" || echo "No changes to commit"
          git push origin data-updates
